image: "debian:buster-slim"

cache: &global_cache
  key: global
  paths:
    - .yarn
    - node_modules
    - data/vicmap.geojson
    - dist/vicmap-osm-uniq-flats.geojson
    - data/victoria-addr.osm.geojson
    - dist/blocksByOSMAddr.geojson
    - data/victoria-admin-level10.osm.geojson

stages:
  - docker
  - prepare
  - build
  - conflate
  - candidate
  - upload

docker prepare:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":prepare -f "docker/prepare.Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE":prepare
  after_script:
    - docker logout $CI_REGISTRY
  when: manual
  cache: {}

docker build-vicmap:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":build-vicmap -f "docker/build-vicmap.Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE":build-vicmap
  after_script:
    - docker logout $CI_REGISTRY
  when: manual
  cache: {}

docker build-osm:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":build-osm -f "docker/build-osm.Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE":build-osm
  after_script:
    - docker logout $CI_REGISTRY
  when: manual
  cache: {}

docker conflate:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":conflate -f "docker/conflate.Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE":conflate
  after_script:
    - docker logout $CI_REGISTRY
  when: manual
  cache: {}

docker candidate:
  image: docker:latest
  services:
    - docker:dind
  stage: docker
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":candidate -f "docker/candidate.Dockerfile" .
    - docker push "$CI_REGISTRY_IMAGE":candidate
  after_script:
    - docker logout $CI_REGISTRY
  when: manual
  cache: {}

prepare:
  stage: prepare
  image: "registry.gitlab.com/alantgeo/vicmap2osm:prepare"
  cache:
    <<: *global_cache
    policy: push
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - mkdir -p dist
    - make data/vicmap.geojson
  when: manual

build vicmap:
  stage: build
  image: "registry.gitlab.com/alantgeo/vicmap2osm:build-vicmap"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - yarn run test
    - mkdir -p dist data
    - mkdir -p data/vicmap/ll_gda94/sde_shape/whole/VIC/VMADD/layer
    - touch data/VICMAP_ADDRESS.zip
    - touch data/vicmap/ll_gda94/sde_shape/whole/VIC/VMADD/layer/address.shp
    - touch --no-create data/vicmap.geojson
    - time make dist/vicmap-osm.geojson
    - time make dist/vicmap-osm-uniq.geojson
    - time make dist/vicmap-osm-uniq-flats.geojson
    - time make dist/vicmap-osm-uniq-flats-withinrange.geojson
  when: manual
  artifacts:
    name: "build vicmap"
    paths:
      - dist
      - debug

build osm:
  stage: build
  image: "registry.gitlab.com/alantgeo/vicmap2osm:build-osm"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull-push
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - mkdir -p dist data
    - make dist/blocksByOSMAddr.fgb
    - make dist/blocksByOSMAddr.geojson
    - make data/victoria-admin-level10.osm.geojson
    - make summariseBlocksByOSMAddr
  when: manual
  artifacts:
    name: "build osm"
    paths:
      - dist

conflate:
  stage: conflate
  image: "registry.gitlab.com/alantgeo/vicmap2osm:conflate"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - make dist/conflate
    - wc -l dist/conflate/*.geojson
  when: manual
  artifacts:
    name: "conflate"
    paths:
      - dist

candidate:
  stage: candidate
  image: "registry.gitlab.com/alantgeo/vicmap2osm:candidate"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - make dist/candidate
  when: manual
  artifacts:
    name: "candidate"
    paths:
      - dist

upload dev:
  stage: upload
  image: "registry.gitlab.com/alantgeo/vicmap2osm:candidate"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - ./bin/upload.sh
  when: manual
  artifacts:
    name: "upload"
    paths:
      - uploadLog

build compareSuburb:
  stage: build
  image: "registry.gitlab.com/alantgeo/vicmap2osm:build-osm"
  before_script:
    - ls data dist
  cache:
    <<: *global_cache
    policy: pull
  script:
    - yarn install
    - cp src/polygon-lookup-patch.js node_modules/polygon-lookup/index.js
    - mkdir -p dist data
    - mkdir -p data/vicmap/ll_gda94/sde_shape/whole/VIC/VMADD/layer
    - touch data/VICMAP_ADDRESS.zip
    - touch data/vicmap/ll_gda94/sde_shape/whole/VIC/VMADD/layer/address.shp
    - touch --no-create data/vicmap.geojson
    - time make dist/vicmap-osm.geojson
    - time make dist/vicmapSuburbDiffersWithOSM.geojson
    - rm -f dist/vicmap-osm.geojson
    - make printDifferentSuburbs
  when: manual
  artifacts:
    name: "build compareSuburb"
    paths:
      - dist
      - debug
